// <auto-generated />
using GeekShopping.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShopping.ProductAPI.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20231112231956_Product data seeding")]
    partial class Productdataseeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeekShopping.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryName = "T-Shirt",
                            Description = "Camisa do Iron Maiden",
                            ImageUrl = "https://static.lojaconsuladodorock.com.br/produto/multifotos/hd/20220309144626_7390992610_DZ.jpg",
                            Name = "Camisa",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 2L,
                            CategoryName = "Pants",
                            Description = "Jeans Azul Clássico",
                            ImageUrl = "https://images.bestsellerclothing.in/data/only/15-sep-2022/255136001_g2.jpg?width=1080&height=1355&mode=fill&fill=blur&format=auto  ",
                            Name = "Jeans Azul",
                            Price = 49.9m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "Footwear",
                            Description = "Tênis leve de corrida",
                            ImageUrl = "https://cdn.thewirecutter.com/wp-content/media/2021/10/running-shoes-2048px-3097.jpg",
                            Name = "Tênis de Corrida",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "Jackets",
                            Description = "Jaqueta de Couro",
                            ImageUrl = "https://thursdayboots.com/cdn/shop/products/1024x1024-Womens-Jackets-Racer-Black-102722-1.jpg?v=1667863479",
                            Name = "Jaqueta de Couro",
                            Price = 129.99m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "Electronics",
                            Description = "Mouse Gamer de alta performance",
                            ImageUrl = "https://i.zst.com.br/thumbs/12/31/3a/1730615274.jpg",
                            Name = "Mouse Gamer",
                            Price = 39.99m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "Furniture",
                            Description = "Mesa resistente de escritório",
                            ImageUrl = "https://moveispollo.com.br/wp-content/uploads/2021/03/frente.jpg",
                            Name = "Mesa de Escritório",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryName = "Bags",
                            Description = "Mochila espaçosa de viagem",
                            ImageUrl = "https://m.media-amazon.com/images/I/41+HVMKtPmL._AC_SY1000_.jpg",
                            Name = "Mochila",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 8L,
                            CategoryName = "Accessories",
                            Description = "Relógio de pulso elegante",
                            ImageUrl = "https://boxwebstore.com.br/wp-content/uploads/2021/07/Rolex-GMT-MASTER-II-40mm-3-600x600.jpg",
                            Name = "Relógio de Pulso",
                            Price = 99.99m
                        },
                        new
                        {
                            Id = 9L,
                            CategoryName = "Photography",
                            Description = "Câmera digital compacta",
                            ImageUrl = "https://cdn.awsli.com.br/600x450/1545/1545522/produto/60996689/ddc807c8b6.jpg",
                            Name = "Câmera Digital",
                            Price = 149.99m
                        },
                        new
                        {
                            Id = 10L,
                            CategoryName = "Audio",
                            Description = "Alto falante portátil bluetooth",
                            ImageUrl = "https://www.artis.in/cdn/shop/products/1_f5b3377c-c870-420f-bc6a-5cd4b3a5a7c7.jpg?v=1653639993",
                            Name = "Alto Falante Bluetooth",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = 11L,
                            CategoryName = "Furniture",
                            Description = "Mesa de jantar moderna",
                            ImageUrl = "https://m.media-amazon.com/images/I/71meUAsP6IL._AC_UF1000,1000_QL80_.jpg",
                            Name = "Mesa de Jantar",
                            Price = 299.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
